// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GastNyahp.E2E.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ImportacionDelJSONDeLaMaquetaFeature : object, global::Xunit.IClassFixture<ImportacionDelJSONDeLaMaquetaFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Importación del JSON de la maqueta", @"    El export de la versión anterior (localStorage/Drive) se importa reproduciendo la carga manual como
    comandos: los guards corren, los ids se remapean y el event store queda auditable como si se hubiera
    tipeado todo a mano hasta el punto de guardado del archivo.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ImportacionLegado.feature"
#line hidden
        
        public ImportacionDelJSONDeLaMaquetaFeature(ImportacionDelJSONDeLaMaquetaFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ImportacionLegado.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Importar el JSON reproduce toda la carga hasta su estado final")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Importación del JSON de la maqueta")]
        [global::Xunit.TraitAttribute("Description", "Importar el JSON reproduce toda la carga hasta su estado final")]
        public async global::System.Threading.Tasks.Task ImportarElJSONReproduceTodaLaCargaHastaSuEstadoFinal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Importar el JSON reproduce toda la carga hasta su estado final", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.WhenAsync("importo el JSON de ejemplo de la maqueta", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 8
    await testRunner.ThenAsync("la operación es aceptada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 9
    await testRunner.AndAsync("el resumen de importación reporta 1 banco, 1 tarjeta, 1 cuota, 1 préstamo y 2 mov" +
                        "imientos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 10
    await testRunner.AndAsync("el listado de bancos contiene \"BBVA\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 11
    await testRunner.AndAsync("la cuota importada \"Smart TV\" tiene el mes \"2025-10\" pagado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 12
    await testRunner.AndAsync("la cuota importada \"Smart TV\" tiene el mes \"2025-11\" por $90000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 13
    await testRunner.AndAsync("el gasto \"Coto\" de \"2026-02\" figura por $95000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 14
    await testRunner.AndAsync("el ticket importado \"Super\" de \"2026-02\" totaliza $33000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 15
    await testRunner.AndAsync("el dólar CCL importado quedó en 1250", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="No se importa sobre una familia con datos, salvo con force")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Importación del JSON de la maqueta")]
        [global::Xunit.TraitAttribute("Description", "No se importa sobre una familia con datos, salvo con force")]
        public async global::System.Threading.Tasks.Task NoSeImportaSobreUnaFamiliaConDatosSalvoConForce()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se importa sobre una familia con datos, salvo con force", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
    await testRunner.GivenAsync("un banco \"Galicia\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 19
    await testRunner.WhenAsync("importo el JSON de ejemplo de la maqueta", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 20
    await testRunner.ThenAsync("la operación es rechazada con \"ya tiene datos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 21
    await testRunner.WhenAsync("importo el JSON de ejemplo de la maqueta con force", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 22
    await testRunner.ThenAsync("la operación es aceptada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Importar reemplazando borra lo anterior y queda auditado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Importación del JSON de la maqueta")]
        [global::Xunit.TraitAttribute("Description", "Importar reemplazando borra lo anterior y queda auditado")]
        public async global::System.Threading.Tasks.Task ImportarReemplazandoBorraLoAnteriorYQuedaAuditado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Importar reemplazando borra lo anterior y queda auditado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("un banco \"Galicia\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 26
    await testRunner.AndAsync("un gasto \"Kiosco viejo\" de $500 en \"Comida\" pagado con efectivo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 27
    await testRunner.WhenAsync("importo el JSON de ejemplo de la maqueta reemplazando todo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 28
    await testRunner.ThenAsync("la operación es aceptada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 29
    await testRunner.AndAsync("el listado de bancos contiene \"BBVA\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 30
    await testRunner.AndAsync("el listado de bancos no contiene \"Galicia\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 31
    await testRunner.AndAsync("no hay gastos este mes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 32
    await testRunner.AndAsync("el resumen de importación reporta 1 banco, 1 tarjeta, 1 cuota, 1 préstamo y 2 mov" +
                        "imientos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Una clave de agente no puede importar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Importación del JSON de la maqueta")]
        [global::Xunit.TraitAttribute("Description", "Una clave de agente no puede importar")]
        public async global::System.Threading.Tasks.Task UnaClaveDeAgenteNoPuedeImportar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una clave de agente no puede importar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("una clave de agente llamada \"asistente\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 36
    await testRunner.WhenAsync("la clave de agente \"asistente\" intenta importar el JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 37
    await testRunner.ThenAsync("la operación es prohibida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ImportacionDelJSONDeLaMaquetaFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ImportacionDelJSONDeLaMaquetaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
